name: Tests

on: [pull_request]

jobs:
  run-unit-tests-and-static-analysis:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - cc: gcc-10
            cxx: g++-10
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          sudo apt-get install -y ${{ matrix.compiler.cc }}
          sudo apt-get install -y ${{ matrix.compiler.cxx }}
          sudo apt-get install -y lcov cppcheck clang-tidy-8
      - name: Build & run unit tests
        run: bash test/build_and_run_ut.sh
      - name: Run clang-tidy
        run: |
          run-clang-tidy-8 \
            -p=test/build \
            -j$(nproc) \
            -header-filter=src/* \
            files src/* \
            -export-fixes clang-tidy-fixes.yaml
      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: clang-tidy-fixes.yaml
          request_changes: true
